apiVersion: v1
kind: Service
metadata:
  name: troshka-postgres
  namespace: troshka
  labels:
    app.kubernetes.io/name: troshka-postgres
spec:
  selector:
    app.kubernetes.io/name: troshka-postgres
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None
