apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: troshka-operator
rules:
  - apiGroups: ["troshka.redhat.com"]
    resources: ["troshkaprojects", "troshkanetworks", "troshkavms"]
    verbs: ["*"]
  - apiGroups: ["troshka.redhat.com"]
    resources: ["troshkaprojects/status", "troshkanetworks/status", "troshkavms/status"]
    verbs: ["*"]
  - apiGroups: ["kubevirt.io"]
    resources: ["virtualmachines", "virtualmachineinstances"]
    verbs: ["*"]
  - apiGroups: ["cdi.kubevirt.io"]
    resources: ["datavolumes"]
    verbs: ["*"]
  - apiGroups: ["k8s.cni.cncf.io"]
    resources: ["net-attach-defs"]
    verbs: ["*"]
  - apiGroups: ["route.openshift.io"]
    resources: ["routes"]
    verbs: ["*"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshots"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["namespaces", "pods", "services", "secrets", "configmaps", "persistentvolumeclaims"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
