apiVersion: apps/v1
kind: Deployment
metadata:
  name: troshka-operator
  namespace: troshka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: troshka-operator
  template:
    metadata:
      labels:
        app: troshka-operator
    spec:
      serviceAccountName: troshka-operator
      containers:
        - name: operator
          image: quay.io/redhat-gpte/troshka-operator:production
          command: ["kopf", "run", "operator.py", "--verbose", "--all-namespaces", "--standalone"]
          env:
            - name: IMAGE_TAG
              value: production
          resources:
            requests:
              cpu: "1"
              memory: 1Gi
            limits:
              cpu: "4"
              memory: 2Gi
