{{- if and .Values.deploy .Values.ingress.enabled .Values.auth.basicAuth.enabled .Values.auth.basicAuth.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.auth.basicAuth.secretName | default "troshka-basic-auth" }}
  namespace: {{ include "troshka.namespace" . }}
  labels:
    {{- include "troshka.labels" . | nindent 4 }}
    app.kubernetes.io/component: auth
type: Opaque
stringData:
  auth: {{ htpasswd (.Values.auth.basicAuth.username | default "admin") .Values.auth.basicAuth.password | quote }}
{{- end }}
