{{- if and .Values.deploy .Values.postgres.deploy }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: troshka-postgres
  namespace: {{ include "troshka.namespace" . }}
  labels:
    {{- include "troshka.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  serviceName: troshka-postgres
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: troshka-postgres
  template:
    metadata:
      labels:
        app.kubernetes.io/name: troshka-postgres
        app.kubernetes.io/component: database
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRESQL_USER
              value: troshka
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: troshka-secrets
                  key: postgres-password
            - name: POSTGRESQL_DATABASE
              value: troshka
          volumeMounts:
            - name: data
              mountPath: /var/lib/pgsql/data
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "troshka"]
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 1Gi
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.postgres.storageSize }}
---
apiVersion: v1
kind: Service
metadata:
  name: troshka-postgres
  namespace: {{ include "troshka.namespace" . }}
  labels:
    {{- include "troshka.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: troshka-postgres
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
{{- end }}
