{{- if .Values.deploy }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: troshka-backend
  namespace: {{ include "troshka.namespace" . }}
  labels:
    {{- include "troshka.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
{{- end }}
