sonar.projectKey=com.redhat.rhpds.troshka
sonar.qualitygate.wait=false

sonar.python.version=3.11

sonar.sources=src/backend/app,src/troshkad,src/operator
sonar.tests=src/backend/tests,src/operator/tests,src/troshkad/tests

sonar.exclusions=\
  .github/**,\
  deploy/**,\
  node_modules/**,\
  src/frontend/**,\
  scripts/**,\
  infra/**,\
  **/__pycache__/**,\
  **/alembic/versions/**

sonar.test.inclusions=\
  **/tests/**/*.py,\
  **/test_*.py,\
  **/conftest.py

sonar.python.coverage.reportPaths=coverage.xml,operator-coverage.xml,troshkad-coverage.xml
