apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - oauth-serviceaccount.yaml
  - oauth-proxy-secret.yaml
  - oauth-client.yaml
  - oauth-proxy-deployment.yaml

patchesStrategicMerge:
  - frontend-route-patch.yaml
