apiVersion: v1
kind: ServiceAccount
metadata:
  name: troshka-oauth
  namespace: troshka
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.primary: >-
      {"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"troshka"}}
