apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: troshka-api
  namespace: troshka
  labels:
    app.kubernetes.io/name: troshka
    app.kubernetes.io/component: backend
spec:
  to:
    kind: Service
    name: troshka-backend
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
