---
- name: Delete namespace (cascading delete)
  kubernetes.core.k8s:
    state: absent
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ troshka_namespace }}"
  ignore_errors: true
