apiVersion: v1
kind: Service
metadata:
  name: troshka-s4
  namespace: troshka
  labels:
    app.kubernetes.io/name: troshka-s4
spec:
  selector:
    app.kubernetes.io/name: troshka-s4
  ports:
    - port: 7480
      targetPort: 7480
      name: s3
    - port: 5000
      targetPort: 5000
      name: ui
