"""add deployed_topology to projects

Revision ID: c4d6da4761cd
Revises: 37afa3d5061d
Create Date: 2026-06-05 08:14:50.221699

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c4d6da4761cd"
down_revision: Union[str, Sequence[str], None] = "37afa3d5061d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column(
            "deployed_topology", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "deployed_topology")
    # ### end Alembic commands ###
