"""add user_ssh_keys table

Revision ID: c6db35dc1084
Revises: dbf91986fccb
Create Date: 2026-06-05 17:21:44.735113

"""
from collections.abc import Sequence
from typing import Union

# revision identifiers, used by Alembic.
revision: str = "c6db35dc1084"
down_revision: Union[str, Sequence[str], None] = "dbf91986fccb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
