apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deploy/namespace.yaml
  - deploy/serviceaccount.yaml
  - deploy/clusterrole.yaml
  - deploy/clusterrolebinding.yaml
  - deploy/deployment.yaml
  - crds/troshkaproject.yaml
  - crds/troshkanetwork.yaml
  - crds/troshkavm.yaml
